---
driver:
  name: docker
  use_sudo: false
  provision_command: sudo apt-get install -y rsync

provisioner:
  name: shell
  script: test/integration/bootstrap.sh
  data_path: .

transport:
  name: rsync

verifier:
  name: busser
  ruby_bindir: /usr/bin

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
