---
driver:
  name: vagrant

provisioner:
  name: shell
  script: test/bootstrap.sh
  data_path: .

transport:
  name: rsync

platforms:
  - name: ubuntu-14.04

suites:
  - name: install
  - name: package
