sudo: required

language: ruby
rvm:
  - 2.3.0

services:
  - docker

before_script:
  - eval $(ssh-agent)
  - chmod 0600 test/travis/id_rsa
  - ssh-add test/travis/id_rsa
  - bundle install

script:
  - bundle exec kitchen test

after_failure:
  - test/travis/after_fail.sh
