services:
  console.application:
    class: '\ComponentManager\Console\Application'
    calls:
      - [setContainer, ['@service_container']]
  console.command.install:
    class: '\ComponentManager\Command\InstallCommand'
    arguments:
      - '@package_repository.factory'
      - '@package_source.factory'
      - '@package_format.factory'
      - '@platform'
      - '@filesystem'
      - '@logger'
    tags:
      - { name: 'console.command' }
  console.command.moodle:
    class: '\ComponentManager\Command\MoodleCommand'
    arguments:
      - '@package_repository.factory'
      - '@package_source.factory'
      - '@package_format.factory'
      - '@platform'
      - '@filesystem'
      - '@logger'
    tags:
      - { name: 'console.command' }
  console.command.package:
    class: '\ComponentManager\Command\PackageCommand'
    arguments:
      - '@package_repository.factory'
      - '@package_source.factory'
      - '@package_format.factory'
      - '@moodle_api'
      - '@filesystem'
      - '@http_client'
      - '@platform'
      - '@logger'
    tags:
      - { name: 'console.command' }
  console.command.refresh:
    class: '\ComponentManager\Command\RefreshCommand'
    arguments:
      - '@package_repository.factory'
      - '@package_source.factory'
      - '@package_format.factory'
      - '@platform'
      - '@filesystem'
      - '@logger'
    tags:
    - { name: 'console.command' }
  console.command.run_script:
    class: '\ComponentManager\Command\RunScriptCommand'
    arguments:
      - '@platform'
    tags:
      - { name: 'console.command' }
  filesystem:
    class: '\Symfony\Component\Filesystem\Filesystem'
  http_client:
    class: '\ComponentManager\HttpClient'
    arguments:
      - '@http_client.client'
      - '@http_client.message_factory'
      - '@http_client.uri_factory'
  http_client.client:
    class: '\Http\Client\HttpClient'
    factory: [ 'Http\Adapter\Guzzle6\Client', createWithConfig ]
    arguments:
      - '%http_client.options%'
  http_client.message_factory:
    class: '\Http\Message\MessageFactory\GuzzleMessageFactory'
  http_client.uri_factory:
    class: '\Http\Message\UriFactory\GuzzleUriFactory'
  logger.console.formatter:
    class: '\Bramus\Monolog\Formatter\ColoredLineFormatter'
  moodle_api:
    class: '\ComponentManager\MoodleApi'
    arguments:
      - '@http_client'
  package_format.factory:
    class: '\ComponentManager\PackageFormat\PackageFormatFactory'
    arguments:
      - '@platform'
      - '@filesystem'
  package_repository.factory:
    class: '\ComponentManager\PackageRepository\PackageRepositoryFactory'
    arguments:
      - '@filesystem'
      - '@http_client'
      - '@platform'
  package_source.factory:
    class: '\ComponentManager\PackageSource\PackageSourceFactory'
    arguments:
      - '@platform'
      - '@http_client'
      - '@filesystem'
  platform:
    class: '\ComponentManager\Platform\Platform'
    factory: ['@platform.factory', 'getPlatform']
    arguments:
      - '%platform.name%'
  platform.factory:
    class: '\ComponentManager\Platform\PlatformFactory'
    arguments:
      - '@filesystem'
monolog:
  channels:
    - 'console'
  handlers:
    console:
      type: 'stream'
      path: 'php://stdout'
      formatter: 'logger.console.formatter'
      level: 'debug'
      channels:
        - 'console'
