#!/usr/bin/env php
<?php

/**
 * Moodle component manager.
 *
 * @author Luke Carrier <luke@carrier.im>
 * @copyright 2016 Luke Carrier
 * @license GPL-3.0+
 */

require_once dirname(__DIR__)
        . DIRECTORY_SEPARATOR . 'vendor'
        . DIRECTORY_SEPARATOR . 'autoload.php';

/**
 * Configuration directory.
 *
 * @var string
 */
define('CM_ETC', dirname(__DIR__) . DIRECTORY_SEPARATOR . 'etc');

/** @var \Symfony\Component\DependencyInjection\ContainerBuilder $container */
$container = require CM_ETC . DIRECTORY_SEPARATOR . 'bootstrap.php';

/** @var \ComponentManager\Console\Application $app */
$app = $container->get('console.application');
$app->run();
