#!/usr/bin/env php
<?php

/**
 * Moodle component manager.
 *
 * @author Luke Carrier <luke@carrier.im>
 * @copyright 2016 Luke Carrier
 * @license GPL-3.0+
 */

use ComponentManager\Console\Application;
use Symfony\Component\DependencyInjection\ContainerBuilder;

require_once dirname(dirname(dirname(__DIR__)))
        . DIRECTORY_SEPARATOR . 'autoload.php';

/**
 * Configuration directory.
 *
 * @var string
 */
define('CM_ETC', dirname(__DIR__) . DIRECTORY_SEPARATOR . 'etc');

/** @var ContainerBuilder $container */
$container = require CM_ETC . DIRECTORY_SEPARATOR . 'bootstrap.php';

/** @var Application $app */
$app = $container->get('console.application');
$app->run();
